### ISSUE TITLE
Possibility to expand to multiple servers?

### ISSUE THREAD

**Issue by afeno** [Naphier/pm2_monitor#24]
First of all, great tool!!! I love it!
I have multiple clients (frontend) running. One for each of my servers. Im wondring how difficult could be to allow the posibility to manage all the servers from one client...
I'm looking at the code (very well organized) but I don't have experience with React and it seems to be pretty complexe for me. Any idea about how to start?

Thank you!

**Comment by Naphier** [comment]
That's a cool idea but I do think it'd be a bit of work as this app runs on the same server as PM2 that's managing the app. It is just an alternative to their web interface for this limited scope. For your use case you'd need the metadata from the PM2 running on each server to report to a centralized location. You could probably do this to a database but it would require pretty much a full rework of this. Not so much the UI but the backend.
